version: '3.8'

services:
  rag-chatbot:
    build: .
    container_name: studymate-ai
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

volumes:
  chroma_db: